[package]
name = "antikythera"
version = "0.0.1"
edition = "2021"
description = "antikythera universal cheat engine"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
